import {
  FaWifi,
  FaCoffee,
  FaBath,
  FaParking,
  FaSwimmingPool,
  FaHotdog,
  FaStopwatch,
  FaCocktail,
} from "react-icons/fa";
import images from "../assets";

export const roomData = [
  {
    id: 1,
    name: "Habitación Superior",
    description:
      "Experimenta el máximo confort en nuestra Habitación Superior. Con un espacio de 30 metros cuadrados, esta habitación es ideal para una persona. Disfruta de comodidades como conexión Wifi, café de cortesía y una relajante bañera. Estacionamiento disponible. Acceso a la piscina y al gimnasio. Despierta cada mañana con un delicioso desayuno y comienza tu día en nuestro exclusivo hotel.",
    facilities: [
      { name: "Wifi", icon: FaWifi },
      { name: "Café", icon: FaCoffee },
      { name: "Bañera", icon: FaBath },
      { name: "Estacionamiento", icon: FaParking },
      { name: "Piscina", icon: FaSwimmingPool },
      { name: "Desayuno", icon: FaHotdog },
      { name: "Gimnasio", icon: FaStopwatch },
      { name: "Bebidas", icon: FaCocktail },
    ],
    size: 30,
    maxPerson: 1,
    price: 115,
    image: images.Room1Img,
    imageLg: images.Room1ImgLg,
  },
  {
    id: 2,
    name: "Habitación exclusiva",
    description:
      "Sumérgete en el lujo de nuestra Habitación Exclusiva. Con 70 metros cuadrados, es perfecta para dos personas. Disfruta de servicios como Wifi, café, bañera y estacionamiento. Relájate en nuestra piscina y mantente en forma en el gimnasio. Despiértate con un desayuno delicioso antes de explorar la ciudad. Tu escape exclusivo te espera.",
    facilities: [
      { name: "Wifi", icon: FaWifi },
      { name: "Café", icon: FaCoffee },
      { name: "Bañera", icon: FaBath },
      { name: "Estacionamiento", icon: FaParking },
      { name: "Piscina", icon: FaSwimmingPool },
      { name: "Desayuno", icon: FaHotdog },
      { name: "Gimnasio", icon: FaStopwatch },
      { name: "Bebidas", icon: FaCocktail },
    ],
    size: 70,
    maxPerson: 2,
    price: 220,
    image: images.Room2Img,
    imageLg: images.Room2ImgLg,
  },
  {
    id: 3,
    name: "Habitación Deluxe",
    description:
      "Descubre la elegancia de nuestra Habitación Deluxe. Con un generoso espacio de 50 metros cuadrados, es ideal para tres personas. Disfruta de comodidades modernas como Wifi, café, bañera y estacionamiento. Relájate en la piscina y mantente activo en nuestro gimnasio. Comienza cada día con un delicioso desayuno antes de explorar la ciudad.",
    facilities: [
      { name: "Wifi", icon: FaWifi },
      { name: "Café", icon: FaCoffee },
      { name: "Bañera", icon: FaBath },
      { name: "Estacionamiento", icon: FaParking },
      { name: "Piscina", icon: FaSwimmingPool },
      { name: "Desayuno", icon: FaHotdog },
      { name: "Gimnasio", icon: FaStopwatch },
      { name: "Bebidas", icon: FaCocktail },
    ],
    size: 50,
    maxPerson: 3,
    price: 265,
    image: images.Room3Img,
    imageLg: images.Room3ImgLg,
  },
  {
    id: 4,
    name: "Habitación De Lujo",
    description:
      "Vive la experiencia de nuestra Habitación de Lujo. Con un espacio de 50 metros cuadrados, es perfecta para cuatro personas. Disfruta de comodidades como Wifi, café, bañera y estacionamiento. Accede a la piscina y al gimnasio para una experiencia completa. Despiértate con un delicioso desayuno antes de explorar todo lo que nuestra ciudad tiene para ofrecer.",
    facilities: [
      { name: "Wifi", icon: FaWifi },
      { name: "Café", icon: FaCoffee },
      { name: "Bañera", icon: FaBath },
      { name: "Estacionamiento", icon: FaParking },
      { name: "Piscina", icon: FaSwimmingPool },
      { name: "Desayuno", icon: FaHotdog },
      { name: "Gimnasio", icon: FaStopwatch },
      { name: "Bebidas", icon: FaCocktail },
    ],
    size: 50,
    maxPerson: 4,
    price: 289,
    image: images.Room4Img,
    imageLg: images.Room4ImgLg,
  },
  {
    id: 5,
    name: "Suite De Lujo ",
    description:
      "Disfruta de la grandiosidad en nuestra Suite De Lujo. Con un amplio espacio de 90 metros cuadrados, es perfecta para cinco personas. Servicios exclusivos como Wifi, café, bañera y estacionamiento están a tu disposición. Relájate en la piscina y mantente en forma en el gimnasio. Comienza cada día con un desayuno delicioso antes de explorar la ciudad.",
    facilities: [
      { name: "Wifi", icon: FaWifi },
      { name: "Café", icon: FaCoffee },
      { name: "Bañera", icon: FaBath },
      { name: "Estacionamiento", icon: FaParking },
      { name: "Piscina", icon: FaSwimmingPool },
      { name: "Desayuno", icon: FaHotdog },
      { name: "Gimnasio", icon: FaStopwatch },
      { name: "Bebidas", icon: FaCocktail },
    ],
    size: 90,
    maxPerson: 5,
    price: 320,
    image: images.Room5Img,
    imageLg: images.Room5ImgLg,
  },
  {
    id: 6,
    name: "Suite Deluxe",
    description:
      "Sumérgete en la opulencia de nuestra Suite Deluxe. Con un espacio de 45 metros cuadrados, es ideal para seis personas. Comodidades modernas como Wifi, café, bañera y estacionamiento están a tu alcance. Accede a la piscina y al gimnasio para una experiencia completa. Despiértate con un delicioso desayuno antes de explorar todos los rincones de nuestra ciudad.",
    facilities: [
      { name: "Wifi", icon: FaWifi },
      { name: "Café", icon: FaCoffee },
      { name: "Bañera", icon: FaBath },
      { name: "Estacionamiento", icon: FaParking },
      { name: "Piscina", icon: FaSwimmingPool },
      { name: "Desayuno", icon: FaHotdog },
      { name: "Gimnasio", icon: FaStopwatch },
      { name: "Bebidas", icon: FaCocktail },
    ],
    size: 45,
    maxPerson: 6,
    price: 344,
    image: images.Room6Img,
    imageLg: images.Room6ImgLg,
  },
  {
    id: 7,
    name: "Suite Presindencial",
    description:
      "Experimenta el lujo en su máxima expresión con nuestra Suite Presidencial. Con un generoso espacio de 84 metros cuadrados, es ideal para siete personas. Servicios exclusivos como Wifi, café, bañera y estacionamiento están a tu disposición. Relájate en la piscina y mantente en forma en el gimnasio. Comienza cada día con un desayuno delicioso antes de explorar la ciudad.",
    facilities: [
      { name: "Wifi", icon: FaWifi },
      { name: "Café", icon: FaCoffee },
      { name: "Bañera", icon: FaBath },
      { name: "Estacionamiento", icon: FaParking },
      { name: "Piscina", icon: FaSwimmingPool },
      { name: "Desayuno", icon: FaHotdog },
      { name: "Gimnasio", icon: FaStopwatch },
      { name: "Bebidas", icon: FaCocktail },
    ],
    size: 84,
    maxPerson: 7,
    price: 389,
    image: images.Room7Img,
    imageLg: images.Room7ImgLg,
  },
  {
    id: 8,
    name: "Suite All-Inclusive",
    description:
      "Vive la experiencia completa con nuestra Suite Todo Incluido. Con un espacio de 100 metros cuadrados, es perfecta para ocho personas. Comodidades modernas como Wifi, café, bañera y estacionamiento están a tu alcance. Accede a la piscina y al gimnasio para una experiencia completa. Despiértate con un delicioso desayuno antes de explorar todos los rincones de nuestra ciudad.",
    facilities: [
      { name: "Wifi", icon: FaWifi },
      { name: "Café", icon: FaCoffee },
      { name: "Bañera", icon: FaBath },
      { name: "Estacionamiento", icon: FaParking },
      { name: "Piscina", icon: FaSwimmingPool },
      { name: "Desayuno", icon: FaHotdog },
      { name: "Gimnasio", icon: FaStopwatch },
      { name: "Bebidas", icon: FaCocktail },
    ],
    size: 100,
    maxPerson: 8,
    price: 499,
    image: images.Room8Img,
    imageLg: images.Room8ImgLg,
  },
  {
    id: 9,
    name: "Suite Sureste",
    description:
      "Vive la experiencia completa con nuestra suite más completa. Con un espacio de 120 metros cuadrados, es perfecta para ocho personas. Comodidades modernas como Wifi, café, bañera y estacionamiento están a tu alcance. Accede a la piscina y al gimnasio para una experiencia completa. Despiértate con un delicioso desayuno antes de explorar todos los rincones de nuestra ciudad.",
    facilities: [
      { name: "Wifi", icon: FaWifi },
      { name: "Café", icon: FaCoffee },
      { name: "Bañera", icon: FaBath },
      { name: "Estacionamiento", icon: FaParking },
      { name: "Piscina", icon: FaSwimmingPool },
      { name: "Desayuno", icon: FaHotdog },
      { name: "Gimnasio", icon: FaStopwatch },
      { name: "Bebidas", icon: FaCocktail },
    ],
    size: 120,
    maxPerson: 10,
    price: 799,
    image: images.Room2Img,
    imageLg: images.Room2ImgLg,
  },
];
